import { Photographer, OccasionType } from "./types";

export const OCCASIONS: { label: OccasionType; icon: string; description: string }[] = [
  {
    label: "Wedding",
    icon: "HeartHandshake",
    description: "Grand royal weddings, intimate rituals & sacred vows",
  },
  {
    label: "Pre-Wedding",
    icon: "Compass",
    description: "Scenic romantic escapes, sunset beach & palace shoots",
  },
  {
    label: "Engagement",
    icon: "Sparkles",
    description: "Ring exchanges, cocktail soirées & celebratory joy",
  },
  {
    label: "Destination",
    icon: "Plane",
    description: "Exotic castles, lakeside shores & mountain peaks",
  },
  {
    label: "Traditional & Cultural",
    icon: "Crown",
    description: "Vibrant ethnic ceremonies, Mehendi, Sangeet & heritage",
  },
  {
    label: "Maternity & Baby",
    icon: "Baby",
    description: "Tender bump portraits & newborn timeless moments",
  },
  {
    label: "Fashion & Editorial",
    icon: "Camera",
    description: "High-contrast lookbooks, haute couture & runway vibes",
  },
  {
    label: "Drone & Cinematic",
    icon: "Video",
    description: "4K cinematic films, sweeping aerial vistas & film grading",
  },
  {
    label: "Corporate & Events",
    icon: "Briefcase",
    description: "Conferences, gala dinners & executive portraits",
  },
];

export const PHOTOGRAPHERS: Photographer[] = [
  {
    id: "photo-1",
    name: "Aarav Singhania",
    businessName: "Singhania Royal Visuals",
    slug: "aarav-singhania",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    coverImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=80",
    tagline: "Fine-Art Royal Weddings & Cinematic Heritage Destination Shoots",
    bio: "With over 9 years documenting luxury heritage weddings across Udaipur, Jaipur, Lake Como, and Dubai, I bring an editorial, timeless warmth to every sacred ritual. My aesthetic blends classical royal grandeur with genuine, candid emotional glimpses.",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    willingToTravel: true,
    rating: 4.95,
    reviewsCount: 78,
    experienceYears: 9,
    startingPrice: 1500,
    currency: "USD",
    featured: true,
    verified: true,
    specialties: ["Wedding", "Pre-Wedding", "Traditional & Cultural", "Destination", "Drone & Cinematic"],
    gearList: [
      "Sony Alpha A1 (50MP Dual Body)",
      "Sony FE 85mm f/1.4 GM II",
      "Sony FE 24-70mm f/2.8 GM II",
      "Sony FE 50mm f/1.2 GM",
      "DJI Inspire 3 Drone with CineCore",
      "Profoto B10X OCF Lighting Suite",
    ],
    socialLinks: {
      instagram: "https://instagram.com",
      website: "https://singhaniavisuals.com",
      youtube: "https://youtube.com",
    },
    packages: [
      {
        id: "pkg-1",
        name: "Classic Day Collection",
        price: 1500,
        duration: "Full Single Day (10 Hours)",
        description: "Perfect for intimate weddings, traditional rituals, or single-day celebrations.",
        deliverables: [
          "2 Senior Photographers + 1 Drone Cinematographer",
          "350+ Master Hand-Retouched High-Res Images",
          "Private Online Cloud Gallery (1 Year Hosting)",
          "1 Cinematic 4K Highlight Reel (3-4 mins)",
          "Turnaround time: 3 weeks",
        ],
      },
      {
        id: "pkg-2",
        name: "Grand 3-Day Royal Heritage Experience",
        price: 3800,
        duration: "3 Full Days (Mehendi, Sangeet, Wedding & Reception)",
        description: "Comprehensive coverage for multi-day destination or palace celebrations.",
        deliverables: [
          "Team of 4 (2 Lead Photographers, 1 Candid Specialist, 1 Drone Pilot)",
          "Pre-Wedding Sunset Shoot Included",
          "850+ Fully Graded High-Resolution Keepsakes",
          "Luxury Handcrafted Italian Leather Album (40 Pages)",
          "10-Minute Feature Documentary + 60-Second Instagram Teaser",
          "Priority 14-Day Delivery",
        ],
        isPopular: true,
      },
      {
        id: "pkg-3",
        name: "Cinematic Pre-Wedding Escape",
        price: 900,
        duration: "1.5 Days",
        description: "Romantic destination narrative crafted in serene architectural or natural landscapes.",
        deliverables: [
          "1 Lead Photographer + 1 Cinematographer",
          "3 Location Changes & Outfit Guidance",
          "75 Master Retouched Portraits + Full raw library",
          "60-sec 4K Cinematic Teaser Film",
        ],
      },
    ],
    portfolio: [
      {
        id: "port-1",
        title: "Palace Courtyard Vows",
        occasion: "Wedding",
        imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
        location: "City Palace, Udaipur",
        cameraGear: "Sony A1 • 85mm f/1.4",
        aspectRatio: "portrait",
        description: "Intimate moment during the twilight pheras under cascading marigolds.",
      },
      {
        id: "port-2",
        title: "Desert Sunset Pre-Wedding",
        occasion: "Pre-Wedding",
        imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
        location: "Sam Sand Dunes, Jaisalmer",
        cameraGear: "Sony A1 • 50mm f/1.2",
        aspectRatio: "landscape",
        description: "Golden hour romance amidst the endless rippling dunes.",
      },
      {
        id: "port-3",
        title: "Royal Haldi Splendor",
        occasion: "Traditional & Cultural",
        imageUrl: "https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1200&q=80",
        location: "Neemrana Fort Palace",
        cameraGear: "Sony A1 • 24-70mm f/2.8",
        aspectRatio: "portrait",
        description: "Pure laughter and turmeric joy framed against weathered sandstone.",
      },
      {
        id: "port-4",
        title: "Lake Como Lakeside Vows",
        occasion: "Destination",
        imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1200&q=80",
        location: "Villa Balbianello, Italy",
        cameraGear: "Sony A1 • 35mm f/1.4",
        aspectRatio: "landscape",
        description: "Overlooking the crystalline alpine waters with classic Italian wooden boats.",
      },
    ],
    reviews: [
      {
        id: "rev-1",
        clientName: "Rohan & Devika Malhotra",
        rating: 5,
        date: "October 2025",
        occasion: "Wedding",
        comment: "Aarav captured the emotional heartbeat of our Udaipur wedding. Looking at the gallery brought tears to our eyes. His team was unobtrusive yet captured every subtle glance!",
      },
      {
        id: "rev-2",
        clientName: "Siddharth & Natasha",
        rating: 5,
        date: "December 2025",
        occasion: "Pre-Wedding",
        comment: "Our pre-wedding shoot in Jaisalmer felt like a movie set. Aarav's direction made us feel so comfortable in front of the lens.",
      },
    ],
  },
  {
    id: "photo-2",
    name: "Elena Rostova",
    businessName: "Lumière Atelier Studios",
    slug: "elena-rostova",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    coverImageUrl: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1600&q=80",
    tagline: "Vogue-Inspired Editorial Weddings, Haute Couture & Romantic Escapes",
    bio: "Former Parisian fashion week photographer turned luxury wedding artisan. I treat each wedding day as a high-fashion editorial story with natural light, painterly shadows, and effortless grace.",
    city: "New York",
    state: "NY",
    country: "USA",
    willingToTravel: true,
    rating: 4.98,
    reviewsCount: 112,
    experienceYears: 11,
    startingPrice: 2200,
    currency: "USD",
    featured: true,
    verified: true,
    specialties: ["Wedding", "Fashion & Editorial", "Engagement", "Destination", "Portraits & Headshots"],
    gearList: [
      "Hasselblad X2D 100C Medium Format",
      "Canon EOS R5 C Dual Setup",
      "Canon RF 50mm f/1.2L USM",
      "Canon RF 28-70mm f/2L USM",
      "Leica M11 Rangefinder",
    ],
    socialLinks: {
      instagram: "https://instagram.com",
      website: "https://lumiereatelier.com",
    },
    packages: [
      {
        id: "pkg-4",
        name: "Editorial Elegance Collection",
        price: 2200,
        duration: "8 Hours",
        description: "Tailored for sophisticated city celebrations and modern architectural venues.",
        deliverables: [
          "Elena Rostova as Lead Artist + 1 Associate",
          "Medium format film portraits included",
          "400+ Curated high-resolution editorial files",
          "Next-day sneak peek gallery (20 portraits)",
        ],
      },
      {
        id: "pkg-5",
        name: "Global Haute Couture Wedding",
        price: 4800,
        duration: "2 Full Days",
        description: "Comprehensive destination coverage anywhere in the world.",
        deliverables: [
          "Team of 3 artists with medium format digital & 35mm film",
          "Rehearsal dinner & cocktail party coverage",
          "Custom linen museum archival box with 50 prints",
          "600+ hand-color-graded heirlooms",
        ],
        isPopular: true,
      },
    ],
    portfolio: [
      {
        id: "port-5",
        title: "Metropolitan Rooftop Sunset",
        occasion: "Wedding",
        imageUrl: "https://images.unsplash.com/photo-1519228251551-80c11d137f84?auto=format&fit=crop&w=1200&q=80",
        location: "Manhattan, New York",
        cameraGear: "Hasselblad X2D • 55mm f/2.5",
        aspectRatio: "portrait",
        description: "Editorial silhouette as dusk settles over the Manhattan skyline.",
      },
      {
        id: "port-6",
        title: "Château de Chantilly Romance",
        occasion: "Destination",
        imageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?auto=format&fit=crop&w=1200&q=80",
        location: "Chantilly, France",
        cameraGear: "Canon R5 • 85mm f/1.2",
        aspectRatio: "landscape",
        description: "Timeless black and white couture gown flowing down grand marble stairs.",
      },
      {
        id: "port-7",
        title: "Autumn Editorial Bridal Veil",
        occasion: "Fashion & Editorial",
        imageUrl: "https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=1200&q=80",
        location: "Central Park Conservatory",
        cameraGear: "Leica M11 • 50mm f/1.4",
        aspectRatio: "portrait",
        description: "Delicate lace catching soft northern window illumination.",
      },
    ],
    reviews: [
      {
        id: "rev-3",
        clientName: "Claire & Julian Sterling",
        rating: 5,
        date: "November 2025",
        occasion: "Wedding",
        comment: "Elena's eye is unparalleled. Our photos look straight out of Vogue! She made everyone look majestic, calm, and breathtaking.",
      },
    ],
  },
  {
    id: "photo-3",
    name: "Vikramaditya Bose",
    businessName: "Bose Candid Chronicles",
    slug: "vikramaditya-bose",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    coverImageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1600&q=80",
    tagline: "Unscripted Raw Emotion • Destination Weddings & Traditional Festivities",
    bio: "No awkward poses, no stiff rehearsals. I capture the raw tears, roaring laughter, spontaneous bhangra moves, and tender whispers that truly define wedding day memories.",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    willingToTravel: true,
    rating: 4.92,
    reviewsCount: 94,
    experienceYears: 8,
    startingPrice: 1100,
    currency: "USD",
    featured: false,
    verified: true,
    specialties: ["Wedding", "Traditional & Cultural", "Pre-Wedding", "Maternity & Baby"],
    gearList: [
      "Nikon Z9 Flagship Bodies",
      "Nikkor Z 58mm f/0.95 Noct",
      "Nikkor Z 35mm f/1.8 S",
      "Godox AD600 Pro Strobe Kits",
    ],
    socialLinks: {
      instagram: "https://instagram.com",
      website: "https://bosechronicles.in",
    },
    packages: [
      {
        id: "pkg-6",
        name: "Pure Candid Day Package",
        price: 1100,
        duration: "10 Hours",
        description: "100% natural candid documentation of all wedding proceedings.",
        deliverables: [
          "2 Candid Specialists",
          "300+ Raw-Emotion Color-Graded Deliverables",
          "Cloud Storage with High-Speed Downloads",
        ],
        isPopular: true,
      },
      {
        id: "pkg-7",
        name: "Festive Multi-Ceremony Package",
        price: 2400,
        duration: "2 Full Days",
        description: "Complete Sangeet, Haldi, Wedding, and Reception storytelling.",
        deliverables: [
          "3 Candid Storytellers + Drone coverage",
          "600+ Edited Stills + High-Res RAW back-up",
          "Signature Flush-Mount Wooden Album",
        ],
      },
    ],
    portfolio: [
      {
        id: "port-8",
        title: "Tearful Vidai Whisper",
        occasion: "Wedding",
        imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
        location: "Mumbai",
        cameraGear: "Nikon Z9 • 58mm f/0.95",
        aspectRatio: "portrait",
        description: "An emotional embrace between father and bride.",
      },
      {
        id: "port-9",
        title: "Sangeet Euphoria",
        occasion: "Traditional & Cultural",
        imageUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1200&q=80",
        location: "Goa Beachfront",
        cameraGear: "Nikon Z9 • 35mm f/1.8",
        aspectRatio: "landscape",
        description: "High energy choreography under celebratory pyrotechnics.",
      },
    ],
    reviews: [
      {
        id: "rev-4",
        clientName: "Ananya & Kunal",
        rating: 5,
        date: "January 2026",
        occasion: "Wedding",
        comment: "Vikram was everywhere without ever being in the way. He captured fleeting moments we didn't even notice happened! 10/10 recommendation.",
      },
    ],
  },
  {
    id: "photo-4",
    name: "Maya Chen",
    businessName: "Seraphic Golden Light",
    slug: "maya-chen",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    coverImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1600&q=80",
    tagline: "Natural Light Magic • Romantic Pre-Weddings & Dreamy Maternity",
    bio: "Specializing in soft golden hour light, coastal dunes, and warm emotional connections. I craft gentle, poetic imagery for maternity, couple engagements, and intimate vows.",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    willingToTravel: true,
    rating: 4.96,
    reviewsCount: 65,
    experienceYears: 7,
    startingPrice: 850,
    currency: "USD",
    featured: true,
    verified: true,
    specialties: ["Pre-Wedding", "Maternity & Baby", "Engagement", "Wedding"],
    gearList: [
      "Canon R6 Mark II Dual",
      "Canon RF 50mm f/1.2L",
      "Canon RF 135mm f/1.8L",
      "Vintage Carl Zeiss Lenses",
    ],
    socialLinks: {
      instagram: "https://instagram.com",
      website: "https://mayachenphoto.com",
    },
    packages: [
      {
        id: "pkg-8",
        name: "Golden Hour Maternity Journey",
        price: 850,
        duration: "3 Hours",
        description: "Intimate coastal or garden session celebrating motherhood.",
        deliverables: [
          "Wardrobe & styling consultation",
          "50 Hand-curated film-toned images",
          "Print release & full-resolution digital gallery",
        ],
      },
      {
        id: "pkg-9",
        name: "Intimate Elopement & Ceremony",
        price: 1800,
        duration: "6 Hours",
        description: "Boutique coverage for cliffside or redwood grove vows.",
        deliverables: [
          "Lead Photographer Maya Chen",
          "250+ Master high-res images",
          "Custom linen album",
        ],
        isPopular: true,
      },
    ],
    portfolio: [
      {
        id: "port-10",
        title: "Pacific Coastline Sunset Bump",
        occasion: "Maternity & Baby",
        imageUrl: "https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=1200&q=80",
        location: "Big Sur, California",
        cameraGear: "Canon R6 II • 135mm f/1.8",
        aspectRatio: "landscape",
        description: "Warm amber glow enveloping the serene ocean cliffside.",
      },
      {
        id: "port-11",
        title: "Golden Gate Twilight Romance",
        occasion: "Pre-Wedding",
        imageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80",
        location: "Marin Headlands",
        cameraGear: "Canon R6 II • 50mm f/1.2",
        aspectRatio: "portrait",
        description: "Windswept veil with golden fog creeping beneath the bridge.",
      },
    ],
    reviews: [
      {
        id: "rev-5",
        clientName: "Jessica & Marcus",
        rating: 5,
        date: "February 2026",
        occasion: "Maternity & Baby",
        comment: "Maya made me feel like an ethereal goddess. The lighting in our maternity shoot is beyond anything we could have dreamed of!",
      },
    ],
  },
  {
    id: "photo-5",
    name: "Kabir Mehra",
    businessName: "AeroLens Cinematics & Drone Studio",
    slug: "kabir-mehra",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    coverImageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1600&q=80",
    tagline: "Ultra-HD 4K Aerial Perspectives & Cinematic Wedding Films",
    bio: "Licensed cinematic drone specialist & colorist. We blend dynamic FPV swoops and grand 8K bird's-eye compositions to elevate palace venues, island ceremonies, and grand baraats into Hollywood-grade experiences.",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    willingToTravel: true,
    rating: 4.89,
    reviewsCount: 52,
    experienceYears: 6,
    startingPrice: 1200,
    currency: "USD",
    featured: false,
    verified: true,
    specialties: ["Drone & Cinematic", "Wedding", "Destination", "Corporate & Events"],
    gearList: [
      "DJI Inspire 3 with Zenmuse X9-8K Air",
      "Custom FPV Cinematic Acro Rig",
      "RED Komodo 6K Cinema Camera",
      "Sony FX6 Cinema Line",
    ],
    socialLinks: {
      instagram: "https://instagram.com",
      youtube: "https://youtube.com",
    },
    packages: [
      {
        id: "pkg-10",
        name: "Aerial Cinema Suite",
        price: 1200,
        duration: "Full Wedding Day",
        description: "Dual-drone team delivering cinematic venue panoramas and baraat sweeps.",
        deliverables: [
          "2 Licensed Drone Pilots",
          "4K Ultra-HD 60fps Aerial Raw Stills & Video",
          "Seamless integration with ground team footage",
        ],
        isPopular: true,
      },
    ],
    portfolio: [
      {
        id: "port-12",
        title: "Palace Island Baraat Aerial",
        occasion: "Drone & Cinematic",
        imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
        location: "Lake Pichola, Udaipur",
        cameraGear: "DJI Inspire 3 • 8K",
        aspectRatio: "landscape",
        description: "Sweeping aerial panorama of lit boats escorting the groom across the royal lake.",
      },
    ],
    reviews: [
      {
        id: "rev-6",
        clientName: "Prateek & Rhea",
        rating: 5,
        date: "December 2025",
        occasion: "Drone & Cinematic",
        comment: "The drone footage Kabir shot of our venue entrance blew all our guests away. It looks like a high-budget Netflix production!",
      },
    ],
  },
];
